-- Pass 27 — Multi-Tenant Clinics
--
-- Hand-written, not autogenerated: this repo has no `prisma/migrations` history (schema
-- has been applied via `prisma db push` per README), so there is no baseline for
-- `prisma migrate diff` to work from. Run `npx prisma validate` against schema.prisma
-- before applying this, and run it against a staging copy of your database first.
--
-- MariaDB DDL is largely NOT transactional (unlike PostgreSQL) — take a real backup
-- before running this against any database with data you care about.
--
-- Ordering matters: nullable columns first, then backfill, then constraints. Do not
-- reorder — Step 5 will fail loudly (as intended) if Step 4 hasn't run correctly.

-- ============================================================================
-- STEP 1 — New tables (purely additive, safe on its own)
-- ============================================================================

CREATE TABLE `Clinic` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `status` ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  `gmailAppEmail` VARCHAR(191) NULL,
  `gmailAppPassEnc` VARCHAR(191) NULL,
  `imageProvider` ENUM('NONE','CLOUDINARY','IMAGEKIT') NOT NULL DEFAULT 'NONE',
  `imageCloudName` VARCHAR(191) NULL,
  `imageApiKeyEnc` VARCHAR(191) NULL,
  `imageApiSecretEnc` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Clinic_slug_key`(`slug`)
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE `DoctorClinic` (
  `id` VARCHAR(191) NOT NULL,
  `doctorId` VARCHAR(191) NOT NULL,
  `clinicId` VARCHAR(191) NOT NULL,
  `approvalStatus` ENUM('PENDING_APPROVAL','APPROVED','REJECTED','SUSPENDED','DEACTIVATED') NOT NULL DEFAULT 'PENDING_APPROVAL',
  `approvalStatusChangedAt` DATETIME(3) NULL,
  `approvalStatusChangedBy` VARCHAR(191) NULL,
  `approvalStatusChangeReason` VARCHAR(191) NULL,
  `joinedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `DoctorClinic_doctorId_clinicId_key`(`doctorId`, `clinicId`),
  INDEX `DoctorClinic_clinicId_approvalStatus_idx`(`clinicId`, `approvalStatus`),
  CONSTRAINT `DoctorClinic_doctorId_fkey` FOREIGN KEY (`doctorId`) REFERENCES `Doctor`(`id`) ON DELETE CASCADE,
  CONSTRAINT `DoctorClinic_clinicId_fkey` FOREIGN KEY (`clinicId`) REFERENCES `Clinic`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

-- ============================================================================
-- STEP 2 — Add clinicId as NULLABLE everywhere first (safe on existing rows)
-- ============================================================================

ALTER TABLE `Auth` ADD COLUMN `clinicId` VARCHAR(191) NULL, ADD INDEX `Auth_clinicId_idx`(`clinicId`);
ALTER TABLE `Patient` ADD COLUMN `clinicId` VARCHAR(191) NULL;
ALTER TABLE `Appointments` ADD COLUMN `clinicId` VARCHAR(191) NULL;
ALTER TABLE `DoctorTimeSlot` ADD COLUMN `clinicId` VARCHAR(191) NULL;

-- Additive enum value — existing 'admin' rows are unaffected.
ALTER TABLE `Auth` MODIFY COLUMN `role` ENUM('super_admin','admin','patient','doctor') NOT NULL;

-- ============================================================================
-- STEP 3 — Backfill: everything that exists today came from one real business.
-- Point all existing rows at a single "Legacy Clinic" so nothing is orphaned.
-- Rename it to your actual clinic's real name/slug before running in production.
-- ============================================================================

INSERT INTO `Clinic` (`id`, `name`, `slug`, `status`, `updatedAt`)
VALUES (UUID(), 'Legacy Clinic', 'legacy-clinic', 'ACTIVE', CURRENT_TIMESTAMP(3));

SET @legacy_clinic_id = (SELECT `id` FROM `Clinic` WHERE `slug` = 'legacy-clinic' LIMIT 1);

UPDATE `Patient` SET `clinicId` = @legacy_clinic_id WHERE `clinicId` IS NULL;
UPDATE `Appointments` SET `clinicId` = @legacy_clinic_id WHERE `clinicId` IS NULL;
UPDATE `DoctorTimeSlot` SET `clinicId` = @legacy_clinic_id WHERE `clinicId` IS NULL;
UPDATE `Auth` SET `clinicId` = @legacy_clinic_id WHERE `role` = 'admin' AND `clinicId` IS NULL;

-- Every existing doctor gets a DoctorClinic row at the legacy clinic, carrying over
-- their current (global) approval status before that column is dropped from Doctor.
INSERT INTO `DoctorClinic`
  (`id`, `doctorId`, `clinicId`, `approvalStatus`,
   `approvalStatusChangedAt`, `approvalStatusChangedBy`, `approvalStatusChangeReason`, `joinedAt`)
SELECT UUID(), `id`, @legacy_clinic_id, `approvalStatus`,
       `approvalStatusChangedAt`, `approvalStatusChangedBy`, `approvalStatusChangeReason`, `createdAt`
FROM `Doctor`;

-- Sanity check before continuing — both should return 0.
-- SELECT COUNT(*) FROM `Patient` WHERE `clinicId` IS NULL;
-- SELECT COUNT(*) FROM `Appointments` WHERE `clinicId` IS NULL;

-- ============================================================================
-- STEP 4 — Now that every row has a clinicId, enforce it for real.
-- ============================================================================

ALTER TABLE `Patient`
  MODIFY COLUMN `clinicId` VARCHAR(191) NOT NULL,
  ADD INDEX `Patient_clinicId_idx`(`clinicId`),
  ADD CONSTRAINT `Patient_clinicId_fkey` FOREIGN KEY (`clinicId`) REFERENCES `Clinic`(`id`);

ALTER TABLE `Appointments`
  MODIFY COLUMN `clinicId` VARCHAR(191) NOT NULL,
  ADD INDEX `Appointments_clinicId_status_idx`(`clinicId`, `status`),
  ADD CONSTRAINT `Appointments_clinicId_fkey` FOREIGN KEY (`clinicId`) REFERENCES `Clinic`(`id`);

ALTER TABLE `DoctorTimeSlot`
  MODIFY COLUMN `clinicId` VARCHAR(191) NOT NULL,
  ADD INDEX `DoctorTimeSlot_clinicId_idx`(`clinicId`),
  ADD CONSTRAINT `DoctorTimeSlot_clinicId_fkey` FOREIGN KEY (`clinicId`) REFERENCES `Clinic`(`id`);

ALTER TABLE `Auth`
  ADD CONSTRAINT `Auth_clinicId_fkey` FOREIGN KEY (`clinicId`) REFERENCES `Clinic`(`id`);

-- Patient.email: drop the old global unique, replace with per-clinic uniqueness.
ALTER TABLE `Patient` DROP INDEX `Patient_email_key`;
ALTER TABLE `Patient` ADD UNIQUE INDEX `Patient_clinicId_email_key`(`clinicId`, `email`);

-- DoctorTimeSlot: old implicit per-doctor uniqueness on `day` becomes explicit and
-- per-clinic. This will fail loudly if duplicate (doctorId, day) rows already exist —
-- they shouldn't, given there's only the legacy clinic so far, but check first if unsure:
-- SELECT doctorId, day, COUNT(*) FROM DoctorTimeSlot GROUP BY doctorId, day HAVING COUNT(*) > 1;
ALTER TABLE `DoctorTimeSlot` ADD UNIQUE INDEX `DoctorTimeSlot_doctorId_clinicId_day_key`(`doctorId`, `clinicId`, `day`);

-- ============================================================================
-- STEP 5 — Drop the now-migrated columns from Doctor. Do NOT run this until Step 3's
-- DoctorClinic backfill is confirmed correct — this is destructive.
-- ============================================================================

ALTER TABLE `Doctor`
  DROP INDEX `Doctor_approvalStatus_idx`,
  DROP COLUMN `approvalStatus`,
  DROP COLUMN `approvalStatusChangedAt`,
  DROP COLUMN `approvalStatusChangedBy`,
  DROP COLUMN `approvalStatusChangeReason`;
